/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'

const GuestRegisterIndexLazyRouteImport = createFileRoute('/_guest/register/')()
const GuestLoginIndexLazyRouteImport = createFileRoute('/_guest/login/')()
const AuthProfileIndexLazyRouteImport = createFileRoute('/_auth/profile/')()
const AuthChatIndexLazyRouteImport = createFileRoute('/_auth/chat/')()
const GuestPasswordResetIndexLazyRouteImport = createFileRoute(
  '/_guest/password/reset/',
)()
const GuestPasswordForgotIndexLazyRouteImport = createFileRoute(
  '/_guest/password/forgot/',
)()

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRegisterIndexLazyRoute = GuestRegisterIndexLazyRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => GuestRouteRoute,
} as any).lazy(() =>
  import('./routes/_guest/register/index.lazy').then((d) => d.Route),
)
const GuestLoginIndexLazyRoute = GuestLoginIndexLazyRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => GuestRouteRoute,
} as any).lazy(() =>
  import('./routes/_guest/login/index.lazy').then((d) => d.Route),
)
const AuthProfileIndexLazyRoute = AuthProfileIndexLazyRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import('./routes/_auth/profile/index.lazy').then((d) => d.Route),
)
const AuthChatIndexLazyRoute = AuthChatIndexLazyRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import('./routes/_auth/chat/index.lazy').then((d) => d.Route),
)
const GuestPasswordResetIndexLazyRoute =
  GuestPasswordResetIndexLazyRouteImport.update({
    id: '/password/reset/',
    path: '/password/reset/',
    getParentRoute: () => GuestRouteRoute,
  } as any).lazy(() =>
    import('./routes/_guest/password/reset/index.lazy').then((d) => d.Route),
  )
const GuestPasswordForgotIndexLazyRoute =
  GuestPasswordForgotIndexLazyRouteImport.update({
    id: '/password/forgot/',
    path: '/password/forgot/',
    getParentRoute: () => GuestRouteRoute,
  } as any).lazy(() =>
    import('./routes/_guest/password/forgot/index.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof AuthChatIndexLazyRoute
  '/profile': typeof AuthProfileIndexLazyRoute
  '/login': typeof GuestLoginIndexLazyRoute
  '/register': typeof GuestRegisterIndexLazyRoute
  '/password/forgot': typeof GuestPasswordForgotIndexLazyRoute
  '/password/reset': typeof GuestPasswordResetIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof AuthChatIndexLazyRoute
  '/profile': typeof AuthProfileIndexLazyRoute
  '/login': typeof GuestLoginIndexLazyRoute
  '/register': typeof GuestRegisterIndexLazyRoute
  '/password/forgot': typeof GuestPasswordForgotIndexLazyRoute
  '/password/reset': typeof GuestPasswordResetIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_auth/chat/': typeof AuthChatIndexLazyRoute
  '/_auth/profile/': typeof AuthProfileIndexLazyRoute
  '/_guest/login/': typeof GuestLoginIndexLazyRoute
  '/_guest/register/': typeof GuestRegisterIndexLazyRoute
  '/_guest/password/forgot/': typeof GuestPasswordForgotIndexLazyRoute
  '/_guest/password/reset/': typeof GuestPasswordResetIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/profile'
    | '/login'
    | '/register'
    | '/password/forgot'
    | '/password/reset'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/profile'
    | '/login'
    | '/register'
    | '/password/forgot'
    | '/password/reset'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/chat/'
    | '/_auth/profile/'
    | '/_guest/login/'
    | '/_guest/register/'
    | '/_guest/password/forgot/'
    | '/_guest/password/reset/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/register/': {
      id: '/_guest/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestRegisterIndexLazyRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login/': {
      id: '/_guest/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginIndexLazyRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/profile/': {
      id: '/_auth/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileIndexLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/chat/': {
      id: '/_auth/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthChatIndexLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_guest/password/reset/': {
      id: '/_guest/password/reset/'
      path: '/password/reset'
      fullPath: '/password/reset'
      preLoaderRoute: typeof GuestPasswordResetIndexLazyRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/password/forgot/': {
      id: '/_guest/password/forgot/'
      path: '/password/forgot'
      fullPath: '/password/forgot'
      preLoaderRoute: typeof GuestPasswordForgotIndexLazyRouteImport
      parentRoute: typeof GuestRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthChatIndexLazyRoute: typeof AuthChatIndexLazyRoute
  AuthProfileIndexLazyRoute: typeof AuthProfileIndexLazyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthChatIndexLazyRoute: AuthChatIndexLazyRoute,
  AuthProfileIndexLazyRoute: AuthProfileIndexLazyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginIndexLazyRoute: typeof GuestLoginIndexLazyRoute
  GuestRegisterIndexLazyRoute: typeof GuestRegisterIndexLazyRoute
  GuestPasswordForgotIndexLazyRoute: typeof GuestPasswordForgotIndexLazyRoute
  GuestPasswordResetIndexLazyRoute: typeof GuestPasswordResetIndexLazyRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginIndexLazyRoute: GuestLoginIndexLazyRoute,
  GuestRegisterIndexLazyRoute: GuestRegisterIndexLazyRoute,
  GuestPasswordForgotIndexLazyRoute: GuestPasswordForgotIndexLazyRoute,
  GuestPasswordResetIndexLazyRoute: GuestPasswordResetIndexLazyRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
